FROM ollama/ollama:latest

RUN apt update && apt install  bash procps coreutils

# Indítunk egy háttérben futó ollama szervert, várunk kicsit amíg elindul,
# majd lehúzzuk a modelleket, végül leállítjuk a szervert.
RUN (ollama serve &); \
    sleep 5; \
    echo "embedding"; \
    ollama pull nomic-embed-text; \
    echo "llama3.2" ; \
    ollama pull llama3.2 ; \
    echo "llama3.2-vision" ; \
    ollama pull llama3.2-vision; \
    echo "Done" ; \
    pkill ollama

# Ha minden modell sikeresen letöltődött, akkor a CMD-ben már csak a szervert indítjuk.
CMD ["serve"]

